---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    exclude_fingerprints:
      # Ignoring false "Illegal export declaration" issue
      - 50151efaf042a4073de8cc12d888cbbd
  fixme:
    enabled: true
ratings:
  paths:
    - src/**
exclude_paths:
    - "*.js"
    - lib/**/*
    - test/**/*
    - node_modules/**/
